name = "Nightfall"
license = "MIT"
licenselink = "https://github.com/LordMathis/hugo-theme-nightfall//blob/master/LICENSE"
description = "Minimal dark theme for Hugo"
homepage = "https://github.com/LordMathis/hugo-theme-nightfall/"
tags = ["minimal", "dark", "blog", "sass"]
features = ["blog", "sass", "dark"]
min_version = "0.80.0"

[author]
name = "Matúš Námešný"
homepage = "https://namesny.com"
